# Generated by Django 5.0.1 on 2024-02-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0004_alter_socialaccount_id_alter_socialapp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Denov', 'Denov'), ('Guliston', 'Guliston'), ('Jizzax', 'Jizzax'), ('Margilon', "Marg'ilon"), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Nukus', 'Nukus'), ('Olmaliq', 'Olmaliq'), ('Qarshi', 'Qarshi'), ('Qoqan', "Qo'qon"), ('Samarqand', 'Samarqand'), ('Olmaliq', 'Olmaliq'), ('Termiz', 'Termiz'), ('Xiva', 'Xiva')], max_length=20)),
                ('recurrent', models.CharField(choices=[('1', '1 kun'), ('2', '2 kun'), ('3', '3 kun'), ('5', '5 kun')], max_length=10)),
                ('route', models.CharField(choices=[('gmail', 'Gmail orqali'), ('telegram', 'Telegram orqali'), ('juftlik', 'Ikkalasidan ham')], max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.URLField(blank=True, null=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
            options={
                'db_table': 'profilemodel',
            },
        ),
    ]
