# Generated by Django 5.0.1 on 2024-02-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Waqt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilemodel',
            table='Waqt_profilemodel',
        ),
    ]
